export enum ActionTypes {
  ADD_INGREDIENT,
  REMOVE_INGREDIENT,
  SET_FETCHING_START,
  SET_FETCHING_SUCCESS,
  SET_FETCHING_FAILURE,
  SUBMIT_ORDER_START,
  SUBMIT_ORDER_SUCCESS,
  SUBMIT_ORDER_FAILURE,
}
